Arial.ttf replaced with LegacyRuntime.ttf
Arial.ttf was causing errors in unity 2022:

ArgumentException: Arial.ttf is no longer a valid built in font. Please use LegacyRuntime.ttf
UnityEngine.Resources.GetBuiltinResource[T] (System.String path) (at <c2d036c16ca64e0eb93703a3b13e733a>:0)
Microsoft.Maps.Unity.MapCopyrightLayer.UpdateDefaultCopyrights (System.Object sender, System.EventArgs args) (at ./Library/PackageCache/com.microsoft.maps.unity@0.11.2/Runtime/Scripts/MapRenderer/Copyrights/MapCopyrightLayer.cs:107)
Microsoft.Maps.Unity.MapRenderer.Update () (at ./Library/PackageCache/com.microsoft.maps.unity@0.11.2/Runtime/Scripts/MapRenderer/MapRenderer.cs:295)